// Reference list of Holy Cross of Davao College's actual colleges and
// programs, used to populate "Add College"/"Add Program" as a dropdown
// instead of free text -- avoids typos/inconsistent naming when adding
// one that's already known. Matches what's already seeded in this
// project's database; extend these two arrays if a genuinely new
// college or program needs to be addable that isn't listed here yet.

export const HCDC_COLLEGES = [
    { code: 'CCJE', name: 'College of Criminal Justice Education' },
    { code: 'CET', name: 'College of Engineering and Technology' },
    { code: 'CHTM', name: 'College of Hospitality and Tourism Management' },
    { code: 'COME', name: 'College of Maritime Education' },
    { code: 'GS', name: 'Graduate School' },
    { code: 'HUSOCOM', name: 'Humanities, Social Sciences and Communication' },
    { code: 'SBME', name: 'School of Business Management Education' },
    { code: 'STE', name: 'School of Teachers Education' },
]

export const HCDC_PROGRAMS = [
    { code: 'BSCRIM', name: 'Bachelor of Science in Criminology', collegeCode: 'CCJE', degreeLevel: 'Bachelor' },
    { code: 'BLIS', name: 'Bachelor of Library and Information Science', collegeCode: 'CET', degreeLevel: 'Bachelor' },
    { code: 'BSCPE', name: 'Bachelor of Science in Computer Engineering', collegeCode: 'CET', degreeLevel: 'Bachelor' },
    { code: 'BSCS', name: 'Bachelor of Science in Computer Science', collegeCode: 'CET', degreeLevel: 'Bachelor' },
    { code: 'BSECE', name: 'Bachelor of Science in Electronics Engineering', collegeCode: 'CET', degreeLevel: 'Bachelor' },
    { code: 'BSIT', name: 'Bachelor of Science in Information Technology', collegeCode: 'CET', degreeLevel: 'Bachelor' },
    { code: 'BSHM', name: 'Bachelor of Science in Hospitality Management', collegeCode: 'CHTM', degreeLevel: 'Bachelor' },
    { code: 'BSTM', name: 'Bachelor of Science in Tourism Management', collegeCode: 'CHTM', degreeLevel: 'Bachelor' },
    { code: 'BSMT', name: 'Bachelor of Science in Marine Transportation', collegeCode: 'COME', degreeLevel: 'Bachelor' },
    { code: 'DED-EM', name: 'Doctor of Education major in Educational Management', collegeCode: 'GS', degreeLevel: 'Doctoral' },
    { code: 'PHD-THEO', name: 'Doctor of Philosophy in Theology', collegeCode: 'GS', degreeLevel: 'Doctoral' },
    { code: 'PHD-EM', name: 'Doctor of Philosophy major in Educational Management', collegeCode: 'GS', degreeLevel: 'Doctoral' },
    { code: 'MM-NT', name: 'Master in Management (Non-Thesis Program)', collegeCode: 'GS', degreeLevel: "Master's" },
    { code: 'MAED-ECE', name: 'Master of Arts in Education major in Early Childhood Education', collegeCode: 'GS', degreeLevel: "Master's" },
    { code: 'MAED-EM', name: 'Master of Arts in Education major in Educational Management', collegeCode: 'GS', degreeLevel: "Master's" },
    { code: 'MAED-ELT', name: 'Master of Arts in Education major in English Language Teaching', collegeCode: 'GS', degreeLevel: "Master's" },
    { code: 'MAED-SPED1', name: 'Master of Arts in Education major in SpEd Area 1 - Teaching Learners with Auditory Disabilities', collegeCode: 'GS', degreeLevel: "Master's" },
    { code: 'MAED-SPED2', name: 'Master of Arts in Education major in SpEd Area 2 - Teaching Learners with Intellectual Disabilities', collegeCode: 'GS', degreeLevel: "Master's" },
    { code: 'MAED-SPED3', name: 'Master of Arts in Education major in SpEd Area 3 - Teaching Children with Developmental & Behavior Problems', collegeCode: 'GS', degreeLevel: "Master's" },
    { code: 'MAED-SPED5', name: 'Master of Arts in Education major in SpEd Area 5 - Teaching Learners with Learning Disabilities', collegeCode: 'GS', degreeLevel: "Master's" },
    { code: 'MAED-TF', name: 'Master of Arts in Education major in Teaching Filipino', collegeCode: 'GS', degreeLevel: "Master's" },
    { code: 'MAED-GS', name: 'Master of Arts in Education major in Teaching General Science', collegeCode: 'GS', degreeLevel: "Master's" },
    { code: 'MAED-TM', name: 'Master of Arts in Education major in Teaching Mathematics', collegeCode: 'GS', degreeLevel: "Master's" },
    { code: 'MAED-TPE', name: 'Master of Arts in Education major in Teaching Physical Education', collegeCode: 'GS', degreeLevel: "Master's" },
    { code: 'MAED-TSS', name: 'Master of Arts in Education major in Teaching Social Studies', collegeCode: 'GS', degreeLevel: "Master's" },
    { code: 'MAGC', name: 'Master of Arts in Guidance and Counseling', collegeCode: 'GS', degreeLevel: "Master's" },
    { code: 'MAT-RE', name: 'Master of Arts in Theology major in Religious Education', collegeCode: 'GS', degreeLevel: "Master's" },
    { code: 'MAT-TS', name: 'Master of Arts in Theology major in Theological Studies', collegeCode: 'GS', degreeLevel: "Master's" },
    { code: 'MSECON', name: 'Master of Science in Economics', collegeCode: 'GS', degreeLevel: "Master's" },
    { code: 'BACOM-JB', name: 'Bachelor of Arts in Communication specializing in Journalism and Broadcasting', collegeCode: 'HUSOCOM', degreeLevel: 'Bachelor' },
    { code: 'BACOM-NMS', name: 'Bachelor of Arts in Communication specializing in New Media Studies', collegeCode: 'HUSOCOM', degreeLevel: 'Bachelor' },
    { code: 'BACOM-SC', name: 'Bachelor of Arts in Communication specializing in Social Communications', collegeCode: 'HUSOCOM', degreeLevel: 'Bachelor' },
    { code: 'BAECON', name: 'Bachelor of Arts in Economics', collegeCode: 'HUSOCOM', degreeLevel: 'Bachelor' },
    { code: 'BAELS', name: 'Bachelor of Arts in English Language Studies', collegeCode: 'HUSOCOM', degreeLevel: 'Bachelor' },
    { code: 'BAHIST', name: 'Bachelor of Arts in History', collegeCode: 'HUSOCOM', degreeLevel: 'Bachelor' },
    { code: 'BAPHIL', name: 'Bachelor of Arts in Philosophy', collegeCode: 'HUSOCOM', degreeLevel: 'Bachelor' },
    { code: 'BAPOLS', name: 'Bachelor of Arts in Political Science', collegeCode: 'HUSOCOM', degreeLevel: 'Bachelor' },
    { code: 'BSPYCH', name: 'Bachelor of Science in Psychology', collegeCode: 'HUSOCOM', degreeLevel: 'Bachelor' },
    { code: 'BSSW', name: 'Bachelor of Science in Social Work', collegeCode: 'HUSOCOM', degreeLevel: 'Bachelor' },
    { code: 'BSA', name: 'Bachelor of Science in Accountancy', collegeCode: 'SBME', degreeLevel: 'Bachelor' },
    { code: 'BSBA-FM', name: 'Bachelor of Science in Business Administration major in Financial Management', collegeCode: 'SBME', degreeLevel: 'Bachelor' },
    { code: 'BSBA-HRM', name: 'Bachelor of Science in Business Administration major in Human Resource Management', collegeCode: 'SBME', degreeLevel: 'Bachelor' },
    { code: 'BSBA-MM', name: 'Bachelor of Science in Business Administration major in Marketing Management', collegeCode: 'SBME', degreeLevel: 'Bachelor' },
    { code: 'BSCA', name: 'Bachelor of Science in Customs Administration', collegeCode: 'SBME', degreeLevel: 'Bachelor' },
    { code: 'BSMA', name: 'Bachelor of Science in Management Accounting', collegeCode: 'SBME', degreeLevel: 'Bachelor' },
    { code: 'BSREM', name: 'Bachelor of Science in Real Estate Management', collegeCode: 'SBME', degreeLevel: 'Bachelor' },
    { code: 'BECE', name: 'Bachelor of Early Childhood Education', collegeCode: 'STE', degreeLevel: 'Bachelor' },
    { code: 'BEED', name: 'Bachelor of Elementary Education', collegeCode: 'STE', degreeLevel: 'Bachelor' },
    { code: 'BPE', name: 'Bachelor of Physical Education', collegeCode: 'STE', degreeLevel: 'Bachelor' },
    { code: 'BSED-ENG', name: 'Bachelor of Secondary Education major in English', collegeCode: 'STE', degreeLevel: 'Bachelor' },
    { code: 'BSED-FIL', name: 'Bachelor of Secondary Education major in Filipino', collegeCode: 'STE', degreeLevel: 'Bachelor' },
    { code: 'BSED-MATH', name: 'Bachelor of Secondary Education major in Mathematics', collegeCode: 'STE', degreeLevel: 'Bachelor' },
    { code: 'BSED-SCI', name: 'Bachelor of Secondary Education major in Science', collegeCode: 'STE', degreeLevel: 'Bachelor' },
    { code: 'BSED-SS', name: 'Bachelor of Secondary Education major in Social Studies', collegeCode: 'STE', degreeLevel: 'Bachelor' },
    { code: 'BSED-VE', name: 'Bachelor of Secondary Education major in Values Education with Catechetics', collegeCode: 'STE', degreeLevel: 'Bachelor' },
    { code: 'BSNE-GEN', name: 'Bachelor of Special Needs Education Generalist', collegeCode: 'STE', degreeLevel: 'Bachelor' },
]
